#!/bin/sh
# first test script for running/updating all simulations

startStop="IDM IDM_w_noise IDMM IIDM ACC GIPPS OVM FVDM KRAUSS NSM BARL KKW CCS"

cleanmovsim

for ldm in ${startStop}
do
  input="startStop_$ldm"
  echo "input = $input"
  runmovsim -f $input
  gnuplot "startStop_$ldm.gpl"
  read -p pressKey
done;



