#!/bin/bash

run="runapp"
onramp="IDM IDMM IIDM ACC GIPPS OVM VDIFF"
startStop="IDM IDM_w_noise IDMM IIDM ACC GIPPS OVM VDIFF BARL NSM KCA"


#######################################################
function deleteSimOutput(){
    echo "project = $1"
    cd sim
    rm -v $project.*.csv
    cd figs
    rm -v $project.*.eps
    cd ..
    cd ..
}
#######################################################
for m in ${onramp}
do
  proj="startStop_$m"
  echo "project = $proj"
  deleteSimOutput $proj
  $run $proj
  read -p pressKey
done;

#exit


for m in ${onramp}
do
  proj="onramp_$m"
  echo "project = $proj"
  deleteSimOutput $proj
  $run $proj
done;

exit

