#!/bin/sh
#
# example for start script for MovSim core, see http://www.movsim.org
# please specify your path to the target output folder and the target version
# 
java -jar $HOME/workspace/movsim/consumption/target/MovsimConsumption-1.7.0-SNAPSHOT-jar-with-dependencies.jar $@


