#!/bin/sh
#
# example for start script for MovSim viewer, see http://www.movsim.org
# please specify your path to the target output folder and the target version
# 
java -jar $HOME/workspace/movsim/viewer/target/viewer-1.0-jar-with-dependencies.jar $@


